# Generated by Django 4.2.5 on 2023-12-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_name_ar_product_name_en_product_subtitle_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_de',
            field=models.CharField(max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle_de',
            field=models.TextField(max_length=500, null=True, verbose_name='Subtitle'),
        ),
    ]
