# Generated by Django 4.2.5 on 2024-02-19 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_name_de_product_subtitle_de'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-id',)},
        ),
    ]
